In [175]:
import pandas as pd

In [176]:
data=pd.read_csv('Placement.csv')

In [177]:
data.shape

(215, 15)

In [178]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    int64
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(2), object(7)
memory usage: 25.3+ KB

In [179]:
data.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [180]:
data.sample(5)

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
78,79,0,84.00,Others,90.9,Others,Science,64.5,Sci&Tech,No,86.04,Mkt&Fin,59.42,Placed,270000.0
167,168,0,67.90,Others,62.0,Others,Science,67.0,Sci&Tech,Yes,58.10,Mkt&Fin,75.71,Not Placed,NaN
197,198,1,83.96,Others,53.0,Others,Science,91.0,Sci&Tech,No,59.32,Mkt&HR,69.71,Placed,260000.0
2,3,0,65.00,Central,68.0,Central,Arts,64.0,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
16,17,0,63.00,Central,66.2,Central,Commerce,65.6,Comm&Mgmt,Yes,60.00,Mkt&Fin,62.54,Placed,300000.0

In [181]:
data.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [182]:
data.describe()

,sl_no,gender,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,0.353488,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,0.479168,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,0.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,0.000000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,0.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,1.000000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,1.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [183]:
data.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [184]:
data["ssc_b"].unique()

array(['Others', 'Central'], dtype=object)

In [185]:
data["hsc_s"].unique()

array(['Commerce', 'Science', 'Arts'], dtype=object)

In [186]:
data["status"].unique()

array(['Placed', 'Not Placed'], dtype=object)

In [187]:
data["status"].value_counts()

status
Placed        148
Not Placed     67
Name: count, dtype: int64

In [188]:
data=data.drop(['sl_no','ssc_b','hsc_b','degree_t','etest_p','specialisation','mba_p','salary'],axis=1)

In [189]:
data.head()

   gender  ssc_p  hsc_p     hsc_s  degree_p workex      status
0       0  67.00  91.00  Commerce     58.00     No      Placed
1       0  79.33  78.33   Science     77.48    Yes      Placed
2       0  65.00  68.00      Arts     64.00     No      Placed
3       0  56.00  52.00   Science     52.00     No  Not Placed
4       0  85.80  73.60  Commerce     73.30     No      Placed

In [190]:
data["hsc_s"].unique()

array(['Commerce', 'Science', 'Arts'], dtype=object)

In [191]:
data["hsc_s"]= data["hsc_s"].map({'Science':2,'Commerce':1,'Arts':0})

In [192]:
data.sample(10)

     gender  ssc_p  hsc_p  hsc_s  degree_p workex      status
19        0  60.00  67.00      0     70.00    Yes      Placed
82        0  63.00  67.00      1     74.00     No  Not Placed
115       1  73.00  63.00      2     66.00     No      Placed
206       0  41.00  42.00      2     60.00     No  Not Placed
148       1  77.00  86.00      0     56.00     No      Placed
47        0  63.00  60.00      1     57.00    Yes      Placed
203       0  55.68  61.33      1     56.87     No      Placed
55        0  60.40  66.60      2     65.00     No      Placed
123       0  74.00  59.00      1     73.00    Yes      Placed
195       0  66.00  76.00      1     72.00    Yes      Placed

In [193]:
data.head(10)

   gender  ssc_p  hsc_p  hsc_s  degree_p workex      status
0       0  67.00  91.00      1     58.00     No      Placed
1       0  79.33  78.33      2     77.48    Yes      Placed
2       0  65.00  68.00      0     64.00     No      Placed
3       0  56.00  52.00      2     52.00     No  Not Placed
4       0  85.80  73.60      1     73.30     No      Placed
5       0  55.00  49.80      2     67.25    Yes  Not Placed
6       1  46.00  49.20      1     79.00     No  Not Placed
7       0  82.00  64.00      2     66.00    Yes      Placed
8       0  73.00  79.00      1     72.00     No      Placed
9       0  58.00  70.00      1     61.00     No  Not Placed

In [194]:
data['workex'].unique()

array(['No', 'Yes'], dtype=object)

In [195]:
data["workex"]= data["workex"].map({'Yes':1,'No':0})

In [196]:
data.head(10)

   gender  ssc_p  hsc_p  hsc_s  degree_p  workex      status
0       0  67.00  91.00      1     58.00       0      Placed
1       0  79.33  78.33      2     77.48       1      Placed
2       0  65.00  68.00      0     64.00       0      Placed
3       0  56.00  52.00      2     52.00       0  Not Placed
4       0  85.80  73.60      1     73.30       0      Placed
5       0  55.00  49.80      2     67.25       1  Not Placed
6       1  46.00  49.20      1     79.00       0  Not Placed
7       0  82.00  64.00      2     66.00       1      Placed
8       0  73.00  79.00      1     72.00       0      Placed
9       0  58.00  70.00      1     61.00       0  Not Placed

In [197]:
data["status"]= data["status"].map({'Placed':1,'Not Placed':0})

In [198]:
data.head(10)

   gender  ssc_p  hsc_p  hsc_s  degree_p  workex  status
0       0  67.00  91.00      1     58.00       0       1
1       0  79.33  78.33      2     77.48       1       1
2       0  65.00  68.00      0     64.00       0       1
3       0  56.00  52.00      2     52.00       0       0
4       0  85.80  73.60      1     73.30       0       1
5       0  55.00  49.80      2     67.25       1       0
6       1  46.00  49.20      1     79.00       0       0
7       0  82.00  64.00      2     66.00       1       1
8       0  73.00  79.00      1     72.00       0       1
9       0  58.00  70.00      1     61.00       0       0

In [199]:
data.columns

Index(['gender', 'ssc_p', 'hsc_p', 'hsc_s', 'degree_p', 'workex', 'status'], dtype='object')

In [200]:
X = data.drop('status',axis=1)
y = data['status']

In [201]:
from sklearn.model_selection import train_test_split

In [202]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state = 42)

In [223]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LinearRegression

In [224]:
model = LinearRegression()
model.fit(X_train,y_train)

lr = LogisticRegression()
lr.fit(X_train,y_train)

svm =svm.SVC()
svm.fit(X_train,y_train)

knn =KNeighborsClassifier()
knn.fit(X_train,y_train)

dt =DecisionTreeClassifier()
dt.fit(X_train,y_train)

rf =RandomForestClassifier()
rf.fit(X_train,y_train)

gb =GradientBoostingClassifier()
gb.fit(X_train,y_train)

GradientBoostingClassifier()

In [229]:
y_pred=model.predict(X_test)
y_pred1=lr.predict(X_test)
y_pred2=svm.predict(X_test)
y_pred3=knn.predict(X_test)
y_pred4=dt.predict(X_test)
y_pred5=rf.predict(X_test)
y_pred6=gb.predict(X_test)

In [230]:
from sklearn.metrics import accuracy_score

In [233]:
score=model.score(X_train,y_train)
score1=accuracy_score(y_test,y_pred1)
score2=accuracy_score(y_test,y_pred2)
score3=accuracy_score(y_test,y_pred3)
score4=accuracy_score(y_test,y_pred4)
score5=accuracy_score(y_test,y_pred5)
score6=accuracy_score(y_test,y_pred6)

In [234]:
print(score,score1,score2,score3,score4,score5,score6)

0.5041387279719604 0.813953488372093 0.7441860465116279 0.813953488372093 0.7674418604651163 0.813953488372093 0.7906976744186046

In [209]:
final_data=pd.DataFrame({'Models':['LR','SVM','KNN','DT','RF','GB'],'ACC':[score1*100,score2*100,score3*100,score4*100,score5*100,score6*100]})

In [210]:
final_data

  Models        ACC
0     LR  81.395349
1    SVM  74.418605
2    KNN  81.395349
3     DT  76.744186
4     RF  81.395349
5     GB  79.069767

In [211]:
import seaborn as sns

In [218]:
new_data = pd.DataFrame({'gender':98,'ssc_p':98,"hsc_p":98,"hsc_s":2,"degree_p":98,"workex":1},index=[0])

In [219]:
dt =DecisionTreeClassifier()
dt.fit(X,y)

DecisionTreeClassifier()

In [220]:
p = lr.predict(new_data)
print(p)
prob = lr.predict_proba(new_data)
if p == 1:
    print("Placed")
    print(f"You will be placed with Probability of {prob[0][1]:.2f}")
else:
    print("Not Placed")

[0]
Not Placed

In [221]:
prob

array([[1.00000000e+00, 2.47911494e-55]])